### PR TITLE
CIRCLE-5713 - Don't list transitive dependencies in workflows

### PR DESCRIPTION
**Pull request by gordonsyme**

### CODE REVIEW

**Comment by zzak** [comment]
@gordonsyme Do you mean because they already depend on `bundle_dependencies`? It looks like `deploy` does not, that's why it failed

**Comment by gordonsyme** [comment]
`deploy` depends on `rake_test` and `precompile_assets` which both depend on `bundle_dependencies`.

**Comment by gordonsyme** [comment]
AFAICS the deploy job failed here because it was trying to push a ref (`fan-in-fan-out`) that doesn't exist locally. Since this ran on a branch called `gordon/fan-in-fan-out` that ref isn't available when the deploy job ran.
If you look at the workflow for the merged commit it all went fine.

**Comment by zzak** [comment]
Ahh, sorry I missed that. Thank you for explaining!

**Pull request merged**
